### ISSUE TITLE
Pharmaverse Inclusion Criteria Checklist

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#153]
### Hosting & Licensing

- [ ]  Acceptable open source license: [AGPv3](https://github.com/Biogen-Inc/tidyCDISC/blob/master/LICENSE.md)
- [ ]  Hosted publicly: [GitHub](https://github.com/Biogen-Inc/tidyCDISC)

### Documentation

- [ ] Exported [functions must have docs](https://biogen-inc.github.io/tidyCDISC/reference/index.html) that [pass R CMD Check](https://github.com/Biogen-Inc/tidyCDISC/actions/)
- [ ] Package [website](https://biogen-inc.github.io/tidyCDISC/), with [vignettes](https://biogen-inc.github.io/tidyCDISC/articles/index.html)

### Version Compatibility and Dependencies

- [ ] Continuous Integration (CI) action to test [R CMD Check](https://github.com/Biogen-Inc/tidyCDISC/actions/) with extra workflows
- [ ] Incremental, semantic [versioning used](https://github.com/Biogen-Inc/tidyCDISC/blob/d391daff99b7a6642438c1341a77a77ae2a99bdd/dev/02_dev.R#L178), following strategies from r-pkgs.org
- [ ] Dependencies [clearly documented](https://github.com/Biogen-Inc/tidyCDISC/blob/d391daff99b7a6642438c1341a77a77ae2a99bdd/DESCRIPTION#L41-L65), and intentionally limited to the most necessary.

### Support and Maintenance

- [ ]
